### ISSUE TITLE
如果headview为uiscrollview(轮播图)则uiscrollview(轮播图)手势滑动失效

### ISSUE THREAD

**Issue by wade0595** [Huanhoo/HHHorizontalPagingView#1]
如果headview为uiscrollview(轮播图)则uiscrollview(轮播图)手势滑动失效

**Comment by Huanhoo** [comment]
嗯，headerView是独立的一个view，和滑动视图只有监听关系，上下滑动headerView可以达到和滑动下方的scrollView的原理是在hitTest中把headerView的hit视图换成了ScrollView；如果需要横向滑动手势的话，就要牺牲在headerView上的上下滑动事件了。

可以把hitTest方法注释掉

//- (UIView *)hitTest:(CGPoint)point withEvent:(UIEvent *)event {
//    UIView *view = [super hitTest:point withEvent:event];
//    if ([view isDescendantOfView:self.headerView] || [view isDescendantOfView:self.segmentView]) {
//        self.horizontalCollectionView.scrollEnabled = NO;
//  
//        self.currentTouchView = nil;
//        self.currentTouchButton = nil;
//  
//        [self.segmentButtons enumerateObjectsUsingBlock:^(id  _Nonnull obj, NSUInteger idx, BOOL \* _Nonnull stop) {
//            if(obj == view) {
//                self.currentTouchButton = obj;
//            }
//        }];
//        if(!self.currentTouchButton) {
//            self.currentTouchView = view;
//        }else {
//            return view;
//        }
//        return self.currentScrollView;
//    }
//    return view;
//}

**Comment by wade0595** [comment]
我想了好久，都没想到解决同时支持上下左右的办法，如果不想牺牲在headerView上的上下滑动事件，请问要如何处理，麻烦你了

**Comment by Huanhoo** [comment]
抱歉啊，这个确实是无解，目前来看就两种解决方案，一个就是不要上下滑动事件，另一个就是手动控制headerView上的轮播图切换，不让用户手动滑
