### ISSUE TITLE
headerHeight设置失效

### ISSUE THREAD

**Issue by AdwardWong** [Huanhoo/HHHorizontalPagingView#10]
设置这句代码，//    [headerView.headerImageView setContentMode:UIViewContentModeScaleAspectFill];会导如下headerHeight设置失效，出现BUG
[HHHorizontalPagingView pagingViewWithHeaderView:headerView headerHeight:200.f segmentButtons:buttonArray segmentHeight:60 contentViews:@[tableView, collectionView, scrollView]];

**Comment by Huanhoo** [comment]
给headerView.headerImageView的clipsToBounds属性设为YES试试呢？

**Comment by AdwardWong** [comment]
如此高度的问题是解决了，但是[headerView.headerImageView setContentMode:UIViewContentModeScaleAspectFill];这句设置又失效了
remarks: QQ：283006543，有解决方法了麻烦通知我下，我在最近的项目用了你这个工具

**Comment by Huanhoo** [comment]
根本原因其实是图片的比例和头视图不一样导致的，你可以自己裁切视图，变成合适的比例就行了。
