### ISSUE TITLE
加入MJRefresh后的问题

### ISSUE THREAD

**Issue by zhangwen2016** [Huanhoo/HHHorizontalPagingView#11]
我现在想加个MJRefresh  在刷新结束时  会出现segment和contentView 会分离一下的情况 不知道是怎么回事

**Comment by Huanhoo** [comment]
用的是最新的1.2.2版本吗？1.2.2版本解决了一下这个问题

**Comment by zhangwen2016** [comment]
我segment下面的cell会往上欠一点 是因为我用了tabBar的原因吗 求破

**Comment by Huanhoo** [comment]
是刷新导致的？还是默认刚进来就往上藏起来了一点？

**Comment by akerdi** [comment]
作者老大帮我打开了个天，，终于知道一些别的知识了。MJ加上去也没问题，终于大概知道MJ思路是啥了：改的是contentInset，在确定刷新时候才改一下contentInset，用完又改回来。

**Comment by 24KYang** [comment]
我的刷新加上去   只要一走刷新 header的滑动就不好使了

**Comment by Huanhoo** [comment]
是滑不动吗？

**Comment by 24KYang** [comment]
先在改完的样子是 能刷新了 刷新好使  只要我用刷新  header就会上去 一个 mj的header的 高度

**Comment by 24KYang** [comment]
.... 是我外头reload了 然后里面发送通知 快了  导致提前了 所以有点问题 现在好了
