### ISSUE TITLE
hearderView改变导致上下滑动分开

### ISSUE THREAD

**Issue by ZhangGuoMing** [Huanhoo/HHHorizontalPagingView#14]
我做了一个类似朋友圈功能,监听到有未读消息,hearderView会多出一块来提示用户,这部分应该怎么实现比较完美.我现在实现出来 高度变化之后,滑动的时候 segmentView和下面的View会有明显分开的感觉

**Comment by Huanhoo** [comment]
最好不在headerView上多出来一块提醒，而是显示单独的一个view来提醒用户

**Comment by neen-tech** [comment]
if you have buttons on Header view button doesn't contents click event ..

**Comment by Huanhoo** [comment]
#20 @08031992

**Comment by LeesimEverglow** [comment]
同样的问题 我现在需要动态改变这个headerview 的高度  改变之后 下面的tableview 就会有明显的间隙 这样有办法处理么？

**Comment by Huanhoo** [comment]
这个暂时无法解决，后续我再增加动态调高的方法吧，你可以重新初始化一遍HHHorizontalPagingView对象，里边的ScrollView对象应该已经存在了，所以不会太影响效率。
