### ISSUE TITLE
在头部添加MJRefresh碰到的状态栏信息覆盖问题

### ISSUE THREAD

**Issue by snaildance** [Huanhoo/HHHorizontalPagingView#15]
你好。
我这边碰到个需求，如果可以的话告诉我该如何处理。十分感谢。
需求：下拉的时候在HeaderView上面有MJRfresh的状态效果
因此：在tableview的头部加 MjRefresh
`    HHContentTableView *tableView           = [HHContentTableView contentTableView];
      tableView.mj_header= [MJRefreshStateHeader headerWithRefreshingTarget:self refreshingAction:@selector(refreshHeader:)];
`

然后下拉刷新的时候 状态信息 会被segment挡住，可是把mj_header加到headerview上不会触发事件，你有什么好的解决方案吗？ 
不知道描述是否清楚 ，谢谢先。

**Comment by Huanhoo** [comment]
MJRefresh可以调整自身显示的位置，是ignoredScrollViewContentInsetTop这个属性，值越大就越靠上。

**Comment by snaildance** [comment]
十分感谢你的回答。对我非常有价值。你的代码我暂时还没去学习，直接拿来用。能否提供支付宝，我想对你的劳动成果进行付费。十分感谢。🙏

**Comment by Huanhoo** [comment]
谢谢。不用客气，开源就是给大家随便用，互相交流的:)
