### ISSUE TITLE
Move indicator

### ISSUE THREAD

**Issue by mrhaxic** [Huanhoo/HHHorizontalPagingView#17]
I tried to use YSLContainerViewController, but it crashed what I want to do is add line indicator to be in the bottom of segments so when the user start scroll the indicator move based on CGoffset could you help me on this please?

the code is:

`  HHHorizontalPagingView *pagingView = [HHHorizontalPagingView pagingViewWithHeaderView:headerView headerHeight:300.f segmentButtons:buttonArray segmentHeight:60 contentViews:@[self.containerV.view]];`

Crash log:

> 2017-02-11 22:32:54.893 HHHorizontalPagingView[3556:307611] -[UIView contentInset]: unrecognized selector sent to instance 0x7fa8b3100430
> 2017-02-11 22:32:54.897 HHHorizontalPagingView[3556:307611] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[UIView contentInset]: unrecognized selector sent to instance 0x7fa8b3100430'
> *** First throw call stack:
> (
> 	0   CoreFoundation                      0x00000001093aad4b __exceptionPreprocess + 171
> 	1   libobjc.A.dylib                     0x0000000108e0c21e objc_exception_throw + 48
> 	2   CoreFoundation                      0x000000010941af04 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
> 	3   CoreFoundation                      0x0000000109330005 ___forwarding___ + 1013
> 	4   CoreFoundation                      0x00000001093bda08 __forwarding_prep_1___ + 120
> 	5   HHHorizontalPagingView              0x00000001088122ad -[HHHorizontalPagingView configureContentView] + 461
> 	6   HHHorizontalPagingView              0x00000001088113cc +[HHHorizontalPagingView pagingViewWithHeaderView:headerHeight:segmentButtons:segmentHeight:contentViews:] + 2412
> 	7   HHHorizontalPagingView              0x000000010880fbfa -[ViewController viewDidLoad] + 2186
> 	8   UIKit                               0x000000010a083a3d -[UIViewController loadViewIfRequired] + 1258
> 	9   UIKit                               0x000000010a083e70 -[UIViewController view] + 27
> 	10  UIKit                               0x0000000109f4d4b5 -[UIWindow addRootViewControllerViewIfPossible] + 71
> 	11  UIKit                               0x0000000109f4dc06 -[UIWindow _setHidden:forced:] + 293
> 	12  UIKit                               0x0000000109f61519 -[UIWindow makeKeyAndVisible] + 42
> 	13  UIKit                               0x0000000109ed9f8d -[UIApplication _callInitializationDelegatesForMainScene:transitionContext:] + 4818
> 	14  UIKit                               0x0000000109ee00ed -[UIApplication _runWithMainScene:transitionContext:completion:] + 1731
> 	15  UIKit                               0x0000000109edd26d -[UIApplication workspaceDidEndTransaction:] + 188
> 	16  FrontBoardServices                  0x000000010e0776cb __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__ + 24
> 	17  FrontBoardServices                  0x000000010e077544 -[FBSSerialQueue _performNext] + 189
> 	18  FrontBoardServices                  0x000000010e0778cd -[FBSSerialQueue _performNextFromRunLoopSource] + 45
> 	19  CoreFoundation                      0x000000010934f761 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
> 	20  CoreFoundation                      0x000000010933498c __CFRunLoopDoSources0 + 556
> 	21  CoreFoundation                      0x0000000109333e76 __CFRunLoopRun + 918
> 	22  CoreFoundation                      0x0000000109333884 CFRunLoopRunSpecific + 420
> 	23  UIKit                               0x0000000109edbaea -[UIApplication _run] + 434
> 	24  UIKit                               0x0000000109ee1c68 UIApplicationMain + 159
> 	25  HHHorizontalPagingView              0x0000000108819faf main + 111
> 	26  libdyld.dylib                       0x000000010c91f68d start + 1
> 	27  ???                                 0x0000000000000001 0x0 + 1
> )

**Comment by Huanhoo** [comment]
The contentView must be the UIScrollView or the subclass of the UIScrollView. So you should make sure that the containerV.view is the UIScrollView.

**Comment by mrhaxic** [comment]
@Huanhoo I will try to see the subclass, could you just give me an example to go ahead with? it would be appreciated

**Comment by Huanhoo** [comment]
I'm sorry to answer your question so late, because I'm on weekend :)
Now let's see your question.
I guess you want to add a header on the view of the YSLContainerViewController?
I simply read the source code of the YSL, and I found YSL is same as HH except for a header.
YSL and HH also requires different independent views(but YSL requires ViewControllers).
However, YSL and HH can not be used together due to the different way of the implementation. 
so I suggest you to put the independent views(must be UIScrollView) to an array which is the contentViews of HH to achieve the effect what you want.

The code is:
HHHorizontalPagingView *pagingView = [HHHorizontalPagingView pagingViewWithHeaderView:yourHeaderView headerHeight:XXX segmentButtons:buttonArray segmentHeight:XXX contentViews:**the array of your independent scrollViews**];

**Comment by mrhaxic** [comment]
@Huanhoo Dear, thank you for your support and it is much appreciated. Actually I did customise for HH and got the point. I will do a pull request soon for that feature. Thanks again.
