### ISSUE TITLE
初始化时设置的frame没有占满屏幕，contentViews多向下偏移的问题

### ISSUE THREAD

**Issue by hxverygood** [Huanhoo/HHHorizontalPagingView#18]
如下图所示，根据需求，需要空出状态栏的位置，于是设置frame为
```
HHHorizontalPagingView *pagingView = [[HHHorizontalPagingView alloc] initWithFrame:CGRectMake(0., 20.0, [[UIScreen mainScreen] bounds].size.width, [[UIScreen mainScreen] bounds].size.height-20.0)];

```
segmentButtons的位置没有问题，但contentViews多向下偏移了20，请问该如何解决？
谢谢！

![simulator screen shot 2017 3 5 22 19 31](https://cloud.githubusercontent.com/assets/13596059/23588039/012da61c-01f2-11e7-9f94-141d6dc49fd6.png)

**Comment by hxverygood** [comment]
是我把问题想得复杂了，一直以为是约束的问题，找了好久都没找到有什么问题，最后发现只要小小的改动就解决问题了，将initWithFrame:pagingView.frame改为：
```
pagingView.horizontalCollectionView = [[UICollectionView alloc] initWithFrame:[UIScreen mainScreen].bounds collectionViewLayout:layout];
```

**Comment by hxverygood** [comment]
上面的方法只解决了一半的问题，tableView最下面少显示了20

**Comment by Huanhoo** [comment]
用下最新的代码看下；
如果调整之后不可以的话可以试着调整下你tableView的contentInset值
