### ISSUE TITLE
scrollEnable设置为NO时按钮无法点击

### ISSUE THREAD

**Issue by TLcv** [Huanhoo/HHHorizontalPagingView#19]
scrollEnable设置为NO时segment无法切换

**Comment by Huanhoo** [comment]
是设置你自己的scrollView的scrollEnabled为NO吗？

**Comment by TLcv** [comment]
@Huanhoo 就demo里HHHorizontalPagingView的 - (void)scrollEnable:(BOOL)enable方法，headerHeight设置为0或者有值，都会有问题

**Comment by Huanhoo** [comment]
嗯，知道了，这个函数的作用是这样：
如果你当前滚动的视图需要进入编辑模式（比如删除Cell），不希望切换到其他的滚动视图时，可以调用这个函数。

如果你希望只是单纯的禁止滚动，点击按钮还可以进行切换的话，就把self.segmentView.userInteractionEnabled     = NO;这句注释掉吧。

后续可能会换个更清晰一点的函数名字。

**Comment by TLcv** [comment]
@Huanhoo 您好，注释 self.segmentView.userInteractionEnabled = NO 还是没有解决问题，我想达到只通过segmentView不用手势左右滑动切换

**Comment by Huanhoo** [comment]
#pragma mark - Observer
- (void)observeValueForKeyPath:(NSString *)keyPath
                      ofObject:(__unused id)object
                        change:(NSDictionary *)change
                       context:(void *)context {
    
    if(context == &HHHorizontalPagingViewPanContext) {
        
        self.horizontalCollectionView.scrollEnabled = YES;


把这里的
self.horizontalCollectionView.scrollEnabled = YES;
也注释掉吧
