### ISSUE TITLE
如何获取滚动到相应页面的事件

### ISSUE THREAD

**Issue by ShaochongDu** [Huanhoo/HHHorizontalPagingView#2]
能否将滚动到相应视图的事件及点击上部button切换视图的事件开放出来，以便进行数据重新请求和刷新

**Comment by Huanhoo** [comment]
有pagingViewSwitchBlock回调，里边的switchIndex参数就是对应的页面序号

**Comment by ShaochongDu** [comment]
clickEventViewsBlock 这个事件是什么，什么情况下能用到

**Comment by Huanhoo** [comment]
是headView上的控件的点击事件；因为放在headerView上控件自身的点击事件已经给屏蔽了，所以要靠这个回调来获取
