### ISSUE TITLE
tableView is not loaded from the first cell

### ISSUE THREAD

**Issue by mrhaxic** [Huanhoo/HHHorizontalPagingView#23]
Hello again!

when the table view is loaded in the `HHorizontalPagingView`, the `contentOffset.y` is not from the first cell could you please advice?

**Comment by mrhaxic** [comment]
I think the solution is uncomment this line in `configureContentView`

`v.contentOffset = CGPointMake(0., -self.headerViewHeight-self.segmentBarHeight);`

What do you think ?

**Comment by Huanhoo** [comment]
Yes, you are right. I've forgot why I commented this line, I might think that the "contentInset" property should adjust the contentOffset of the ScrollView.
you can uncomment this line to solve your problem, I will update this repository soon.

Thank you very much!

**Comment by mrhaxic** [comment]
@Huanhoo Most welcome, 👍
