### ISSUE TITLE
StretchyFactor for animation purpose

### ISSUE THREAD

**Issue by mrhaxic** [Huanhoo/HHHorizontalPagingView#25]
Dear brother,

We would like to enhance and add nice thing to be used in the header something called StretchyFactor which is help for animation effects for example: change alpha / size / scale / position for any object inside the headerView.

Lets suppose we have UIButton in the headerView and while scrolling down/up we need to change alpha of that UIButton. If the user scrolling to segmentTopSpace so the UIButton alpha will be 0 then if the user scrolling up the alpha will be increase based on StretchyFactor or position.

Hope you got my idea. Am trying to use a sample code in other repository but it doesn't work.

```
CGFloat ownHeight = CGRectGetHeight(self.bounds);
CGFloat contentHeightDif = (self.maximumContentHeight - self.minimumContentHeight);
CGFloat maxContentViewHeight = ownHeight - self.verticalInset;
CGFloat newStretchFactor = (maxContentViewHeight - self.minimumContentHeight) / contentHeightDif;
```

**Comment by Huanhoo** [comment]
There has a block "scrollViewDidScrollBlock" in HHHorizontalPagingView and it will call back when your scrollView scrolling up/down. you can use the variable "offset" to control the alpha of your button.

when your scrollView is in the initial state, the alpha of button should be 1.0f, and the offset of scrollView is - (headerHeight + segmentHeight).

if your scrollView scrolling to segmentTopSpace, the alpha of button should be 0.0f, and the offset of scrollView is -(segmentTopSpace + segmentHeight).

Then you can use the "two point form" (x - x1) / (x2 - x1) = (y - y1) / (y2 - y1) to calculate the alpha value.

(x + (headerHeight + segmentHeight)) / ((-segmentTopSpace - segmentHeight) + (headerHeight + segmentHeight)) = (y - 1) / (0 - 1)

The result is y = 1 - ((x + (headerHeight +segmentHeight )) / (headerHeight - segmentTopSpace))

Make a test:
![38cd3ed3-5018-4f39-8d07-fcbd1109fc7d](https://cloud.githubusercontent.com/assets/3039189/26487248/4cd3c5fe-4231-11e7-9a77-c6d7a79d9b78.png)

The alpha will be changed from 1.f to 0.f when you scrolling to segmentTopSpace.

**Comment by mrhaxic** [comment]
@Huanhoo Thanks alot, your effort is highly appreciated I will make a smoke test and reply soon.

**Comment by mrhaxic** [comment]
Hi @Huanhoo 

Well done, its work fantastic. What do you think if you want to resize an UIImageView or change (y,x) based on scrolling.

Any hint?

Thanks alot

**Comment by Huanhoo** [comment]
if the aspect ratio of the image is consistent, you can use the same way to implement it. "two point form", y2 and y1 is the max or min size of your image

**Comment by mrhaxic** [comment]
Hi,

I tried but unfortunately I didn't get the correct solution and it will be appreciated to explain it with an example.

**Comment by Huanhoo** [comment]
Ok, check this file.
[HHHorizontalPagingView.zip](https://github.com/Huanhoo/HHHorizontalPagingView/files/1186361/HHHorizontalPagingView.zip)

**Comment by mrhaxic** [comment]
Am really don't know how to say Thank you, Really appreciated.

**Comment by Huanhoo** [comment]
:)
