### ISSUE TITLE
My way to solve UIButton Click event

### ISSUE THREAD

**Issue by leavesster** [Huanhoo/HHHorizontalPagingView#27]
在`- (UIView *)hitTest:(CGPoint)point withEvent:(UIEvent *)event `方法中判断headerView中的subview，如果是UIButton或者响应输入文字的，则返回该subview本身。

具体的优化见：
https://leavesster.github.io/%E5%B5%8C%E5%A5%97UISCrollview(%E4%BA%8C)/#优化

**Comment by Huanhoo** [comment]
嗯，当初做的时候考虑过这个问题，也尝试过返回button本身，但是就会导致另一个问题……。就是当手指在headerView上的button上下滑的时候，就不响应滑动手势了，所以如果加入headerView上的button很多，或者很霸屏的时候，那么滑动区域就会缩小很多。

**Comment by leavesster** [comment]
我当初headerview还有输入搜索文本的需求，如果用block的形式，也不是说不行，但是肯定会麻烦不少吧，所以我感觉返回对应类会比较合适。

先选在button上，然后再上下滑动，我有想过，不过感觉真这么干的人应该不多，而且比起高亮丢失和保持原有控件的调用方法，我觉得还是后两者比较重要一些。
感觉也是个人取舍上的关系了。
另外，谢谢你的文章，不然我还得折腾死。

**Comment by Huanhoo** [comment]
因为你在UITableView的tableHeaderView上添加button的话，button也不会阻挡UITableView整体的滑动，所以当时写这个的时候想尽量靠近UITableView一些。

**Comment by leavesster** [comment]
观察了下，网易大概是我这样实现的，button会阻拦滑动。Twitter的button不会。
