### ISSUE TITLE
NSString property in HHHorizontalPagingView.h

### ISSUE THREAD

**Issue by mrhaxic** [Huanhoo/HHHorizontalPagingView#28]
Hi again, 

Thanks in advance for your usual support .. am trying to set NSString as property in HHHorizontalPagingView header file like

`@property (nonatomic, strong) NSString *someText;`

Then I added a method below Setter 

`- (void)setSomeText:(NSString *)someText 
{
    _someText = someText;
}`

after when I set in the controller like `pagingView.someText = @"hi";` it doesn't actually set that value always shown (null).

Thanks again.

**Comment by Huanhoo** [comment]
Has pagingView been initialized?

**Comment by mrhaxic** [comment]
Yes dear
 
`HHHorizontalPagingView *pagingView = [HHHorizontalPagingView pagingViewWithHeaderView:headerView headerHeight:200.f segmentButtons:buttonArray segmentHeight:40.0f contentViews:@[tableView,scrollView,teamTable,matchTable]];`

**Comment by Huanhoo** [comment]
can you send the demo to my mail?  huh519@sina.com

Or you can add a Breakpoint at the "- (void)setSomeText:" function, and check the value after you call it.

**Comment by mrhaxic** [comment]
get null value

**Comment by mrhaxic** [comment]
btw, if I used `NSInteger` it is working fine but `NSString` always return null

**Comment by mrhaxic** [comment]
Deeply debug with breakpoints and got the idea. Thanks alot.
