### ISSUE TITLE
Incorrect CGfloat while quick scrolling (scrollViewDidScrollBlock) bug

### ISSUE THREAD

**Issue by mrhaxic** [Huanhoo/HHHorizontalPagingView#29]
Hi brother,

In the `scrollViewDidScrollBlock` while you scrolling slowly it returns correct **CGfloat** but if you are scrolling fast/quick it returns incorrect **CGfloat**, What do you think ?

Regards

**Comment by Huanhoo** [comment]
really? 
I test it but everything is fine

**Comment by mrhaxic** [comment]
Yes, And instead passing offset I have changed it to Inset and this returns the current header height which is better to use in animations purpose

**Comment by Huanhoo** [comment]
So, you use "current header" instead of "offset" and solved your problem?

**Comment by mrhaxic** [comment]
Yes you are right.
