### ISSUE TITLE
HHHeaderView can add uibutton, but no action

### ISSUE THREAD

**Issue by ahyong87** [Huanhoo/HHHorizontalPagingView#3]
我尝试在HHHeaderView里面加载一个按键，UI有出来，只是我怎样弄也弄不到button的action

**Comment by Huanhoo** [comment]
headerview里的所有点击事件，都要通过clickEventViewsBlock回调来获取，并且不支持滑动事件

**Comment by ahyong87** [comment]
小弟不才，可以知道要怎样调用吗？

2016-02-26 10:09 GMT+08:00 Hu Huan notifications@github.com:

> headerview里的所有点击事件，都要通过clickEventViewsBlock回调来获取，并且不支持滑动事件
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Huanhoo/HHHorizontalPagingView/issues/3#issuecomment-189078664
> .

## 

Best Regards,

_Chong Chee Yong_
Senior Mobile Developer
http://www.chongcheeyong.com
http://www.duckymall.com/profile/

Ducky Mall (002240540-X)
Website: http://duckymall.com

**Comment by Huanhoo** [comment]
_pagingView.clickEventViewsBlock = ^(UIView *eventView){

  if (eventView == xxx) {

  }

 };

就这样调用；_pagingView是你实例化的HHHorizontalPagingView的对象，block里边的eventView就是你点击的视图。然后你在里边判断一下是哪个button，做出相应的动作就好了
