### ISSUE TITLE
space in the initial [iOS 11]

### ISSUE THREAD

**Issue by mrhaxic** [Huanhoo/HHHorizontalPagingView#32]
Hello brother,

There is a space between **segmentView** and the **contentView** in the initial either by click on segmentButton or switching between the pages.

Please look at this image https://d.pr/QV13wj

Any advice?

Regards

**Comment by Huanhoo** [comment]
Hi bro

Thank you for finding this question, I had fixed it and push the code to "master" branch, I will update Pods when I solve the CocoaPods bugs on macOS High Sierra.

Best Regards

**Comment by mrhaxic** [comment]
Hi brother,

It works perfectly, Appreciated.

Regards
