### ISSUE TITLE
Header height got increased during segments event and scrolling

### ISSUE THREAD

**Issue by mrhaxic** [Huanhoo/HHHorizontalPagingView#33]
Hello friend,

I got an issue which increases the section height for `tableView` and it is considered as an empty space if the user clicks on a segment and scroll down/up immediately.

To reproduce this issue please you can do by following steps:

- [ ] 1. Click on another current segment.
- [ ] 2. Once you click the segment try to scroll down/up immediately.

Kindly refer also to the below screenshot:
<img width="512" alt="image" src="https://cdn-std.dprcdn.net/files/acc_581224/DyyAXJ">

**Comment by Huanhoo** [comment]
Hi Bro!

Thanks for your feedback, I have solved it by this way:

![image](https://user-images.githubusercontent.com/3039189/32768398-48b5acf2-c8dd-11e7-96ac-da0c150ac521.png)

The two contentViews can't scroll together,  So I prohibit scrollview sliding when the segment button clicked, and restore the "scrollEnabled" in next runloop.

**Comment by mrhaxic** [comment]
Hi friend,

I will try and lets you know
Thanks a lot for your usual support and quick response

**Comment by Huanhoo** [comment]
No sweat :)
