### ISSUE TITLE
键盘问题

### ISSUE THREAD

**Issue by 24KYang** [Huanhoo/HHHorizontalPagingView#34]
我在cell上加了一个searchBar 然后键盘出现的时候 不管在什么位置 都回到最上方  我设置offset 也不管用

**Comment by mrhaxic** [comment]
Hi @24KYang 
I would like to help, could you please describe your issue in English?

Regards

**Comment by 24KYang** [comment]
My English is too bad,This problem is solved.
I added a notice to HHHorizontalPagingView.m
/*********************纠正弹出键盘bug************************/
- (void)keyboardBug:(NSNotification *)noti {
    NSNumber *status = noti.userInfo[@"status"];
    if (status.boolValue) {
        self.headerView.st_y = - _headerViewHeight + _segmentTopSpace;
        self.segmentView.st_y = _segmentTopSpace;
    }else{
        self.headerView.st_y = 0;
        self.segmentView.st_y = _headerViewHeight ;
        [self.currentScrollView setContentInset:UIEdgeInsetsMake(_headerViewHeight + _segmentBarHeight, 0, 0, 0)];
        [self.currentScrollView setContentOffset:CGPointMake(0, - _headerViewHeight - _segmentBarHeight) animated:NO];
    }
}
/*********************纠正弹出键盘bug************************/


Send notifications in C with a keyboard pop-up
/**
 键盘将要出现  解决搜索列表 偏移bug
 */
- (void)keyboardWillShow:(NSNotification *)notif {
        [self.tableView setContentInset:UIEdgeInsetsMake(64 + CalculateHeight(106), 0, 0, 0)];
        [[NSNotificationCenter defaultCenter] postNotificationName:kHHHorizontalBugNotification object:nil userInfo:@{@"status":@YES}];
}
- (void)keyboardWillHide:(NSNotification *)notif {
        [self.tableView setContentInset:UIEdgeInsetsMake(_fillHeight, 0, 0, 0)];
        [[NSNotificationCenter defaultCenter] postNotificationName:kHHHorizontalBugNotification object:nil userInfo:@{@"status":@NO}];
        [[NSNotificationCenter defaultCenter] postNotificationName:ShowWonderfulSearchBarHiddenNotification object:nil];
}
That's my solution,I use the translation tool!Forgive me!
Thanks!!!

**Comment by 24KYang** [comment]
My problem is that there are keyboard pop-ups on the page there will be a bug, hhhorizontalPagingView  will return to the top, You can try it!

**Comment by mrhaxic** [comment]
@24KYang  could you share your Xcode project to reproduce the issue

**Comment by 24KYang** [comment]
I've been a little busy lately,I write the problem in demo at the weekend.Give me email!

**Comment by Huanhoo** [comment]
嗯……这是个已知问题，在修改UIScrollView的contentInset的情况下弹出键盘就会遇到这个坑，你能通过别的方法规避太好了！
