### ISSUE TITLE
fixe width issue and more no. segments..

### ISSUE THREAD

**Issue by prakashmaharjan** [Huanhoo/HHHorizontalPagingView#36]
When added more no of segments, then it overlap each other as width is fixed..

![simulator screen shot - iphone 7 plus - 2018-02-05 at 17 17 00](https://user-images.githubusercontent.com/8100150/35802486-64b8a98e-0a98-11e8-9632-266f5e7ba359.png)

**Comment by Huanhoo** [comment]
Oops, This issue is a known yet, you should change the SegmentView to a ScrollView.
And I m thinking to improve this code and may fix this issue later.

**Comment by prakashmaharjan** [comment]
Thanks for reply...Where do we change that?
Hope to get the new update soon.
Thank you 👍

**Comment by Huanhoo** [comment]
You can create a ScrollView object in the method "configureSegmentButtonLayout:" in "HHHorizontalPagingView.m" file. and put all of buttons on it.
