### ISSUE TITLE
我想动态控制头部图片位置

### ISSUE THREAD

**Issue by LisaJasmine** [Huanhoo/HHHorizontalPagingView#7]
我想动态控制头部的高度，这个应该如何做？求教

**Comment by Huanhoo** [comment]
暂时无法 只能重新创建一个

**Comment by LisaJasmine** [comment]
亲，如果我想在你的segmentButton下面加一条长线点击的时候会移动的那种的话这个，应该写在什么方法里呢

**Comment by Huanhoo** [comment]
加在configureSegmentButtonLayout函数里就好，然后在scrollViewDidScroll回调里控制长线的位移
