### ISSUE TITLE
headview添加按钮之后获取不到点击事件

### ISSUE THREAD

**Issue by LabelChuang** [Huanhoo/HHHorizontalPagingView#8]

**Comment by Huanhoo** [comment]
点击事件需要通过clickEventViewsBlock这个block获取，可以在头文件里找到这个block

**Comment by LabelChuang** [comment]
我想在按钮下面添加一个滑动的view来提示选中的第几个页面请问在哪个方法里面添加？ 今天找了两个小时没找到

**Comment by Huanhoo** [comment]
这个需求只能改源码了，加在configureSegmentButtonLayout函数里就好，然后在scrollViewDidScroll回调里控制长线的位移；
后续我也会添加这个功能进去 :)

**Comment by LabelChuang** [comment]
好的有更新望通知 现在项目基本完成就等你这个加上去了 啊哈哈

**Comment by LabelChuang** [comment]
发现一个BUG 当导航栏和tabbar同时存在的时候会出现按钮盖住下面视图的情况

**Comment by Huanhoo** [comment]
想象不到你这个是什么情况，我这边也有导航和tabbar同时存在的 但是没出现什么问题，你可以下载我们的app 口袋饭 看看
